### ISSUE TITLE
Add support for new field `jsonValue` recenly added inside metafields/metaobjects

### ISSUE THREAD

**Issue by muchisx** [Shopify/graphql-codegen#13]
Currenlty getting this errors even if the version is set to to `2024-07`

![image](https://github.com/user-attachments/assets/9b0bf0d1-cc65-4564-9f07-f9c29cddf611)

Here's docs that point to the new field
https://shopify.dev/changelog/new-metafield-jsonvalue-field

**Comment by frandiox** [comment]
Hi 👋  -- I don't think this is related to codegen since you are getting the error directly on the GraphQL schema. Are you perhaps using https://github.com/shopify/shopify-app-js to generate the Admin schema? cc @paulomarg

**Comment by frandiox** [comment]
The error you see probably comes from an editor plugin such as https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql .

These plugins are reading your GraphQL query and comparing it to the Admin API GraphQL Schema, showing you errors for missing fields. The Admin API schema is what you probably have generated in a `.json` file when using  https://github.com/shopify/shopify-app-js . Therefore, the problem is either in the API itself or in the package that generates the JSON schema.

What we do in this repo is reading that that same `.json` schema to generate types for autocompletion at the TypeScript level. What you see in that error is at the GraphQL level, so it must come from the JSON schema.

Let's see if @paulomarg has more insights.
